name: "Hackage, Cabal, Linux"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "45 02 * * *"


jobs:

  build10:
    name: "GHC"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        packageRoot: [ hnix-store-core, hnix-store-remote ]
        ghc: [ "8.10", "8.4" ]
    defaults:
      run:
        working-directory: "./${{ matrix.packageRoot }}"
    steps:
      - uses: actions/checkout@v2
      - name: "Cache of ~/.cabal/packages, ~/.cabal/store and dist-newstyle"
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: "${{ runner.os }}-Cabal-${{ matrix.ghc }}"
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: "Install additional system packages"
        run: sudo apt install libsodium-dev
      - run: cabal v2-install tasty-discover
      - name: "Install Nix"
        # Still required for Store-remote test suite run
        uses: cachix/install-nix-action@v12
        if: matrix.packageRoot == 'hnix-store-remote'
      - run: cabal v2-configure --disable-optimization --enable-tests --enable-deterministic
        if: matrix.packageRoot == 'hnix-store-core'
      - run: |
          cabal v2-configure --disable-optimization --enable-tests --enable-deterministic \
            -f io-testsuite  # Enable the Store-remote test suite
        if: matrix.packageRoot == 'hnix-store-remote'
      - run: cabal v2-build
      - run: cabal v2-test
