name: "Release testing, Hackage, Cabal, Linux"

on:
  release:
    # created: a draft is saved, or a release or pre-release is published without previously being saved as a draft
    types: [ created ]

jobs:

  build10:
    name: "GHC"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        packageRoot: [ hnix-store-core, hnix-store-remote ]
        # Since CI by default tests boundary GHCs, test middle versions of GHCs
        ghc: [ "8.8", "8.6"]
    defaults:
      run:
        working-directory: "./${{ matrix.packageRoot }}"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache of ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-Cabal-${{ matrix.ghc }}
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: "Install additional system packages"
        run: sudo apt install libsodium-dev
      - run: cabal v2-install tasty-discover
      - run: cabal v2-configure --disable-optimization --enable-tests --enable-deterministic
        if: matrix.packageRoot == 'hnix-store-core'
      - run: |
          cabal v2-configure --disable-optimization --enable-tests --enable-deterministic \
            -f io-testsuite  # Enable the Store-remote test suite
        if: matrix.packageRoot == 'hnix-store-remote'
      - run: cabal v2-build
      - run: cabal v2-test
